#version: "3.8" 
#since docker no longer needs to specify the version

services:
  # --- Database Service ---
  postgres:
    image: postgres:17
    #changed the version from 16 to 17 for the transaction_timeout feature
    container_name: sddms_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      #- ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
      - ./database/SIH_DATABASE.sql:/docker-entrypoint-initdb.d/01_sih_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Object Storage Service ---
  minio:
    image: minio/minio:latest
    container_name: sddms_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - miniodata:/data
    
  # --- Antivirus Scanner Service ---
  clamav:
    image: clamav/clamav:latest
    container_name: sddms_clamav
    ports:
      - "3310:3310"
    volumes:
      - clamdata:/var/lib/clamav
    healthcheck:
      test: ["CMD", "sh", "-c", "echo PING | nc localhost 3310"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- Application Backend ---
  backend:
    build: ./backend
    #.env file is also needed in backened folder therefore instead of copying it to backend folder, we can use env_file to load the environment variables from the .env file in the root directory
    env_file:
      - .env
    container_name: dms_backend
    # Explicitly run Uvicorn with multiple workers and no --reload in production for better performance and stability
    #command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ENABLE_SSE: ${MINIO_ENABLE_SSE}
      CLAMAV_HOST: clamav
      CLAMAV_PORT: ${CLAMAV_PORT}
      ENABLE_AV_SCAN: ${ENABLE_AV_SCAN}
      MAX_FILE_SIZE_BYTES: ${MAX_FILE_SIZE_BYTES}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started 
      clamav:
        condition: service_healthy 
      
  # --- Application Frontend ---
  frontend:
    build: ./frontend
    container_name: dms_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

volumes:
  pgdata:
  miniodata:
  clamdata: