-- 03_indexes.sql
BEGIN;
CREATE INDEX IF NOT EXISTS idx_user_departments_user ON user_departments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_department ON user_departments(department_id);
CREATE INDEX IF NOT EXISTS idx_user_departments_role ON user_departments(role_id);
CREATE INDEX IF NOT EXISTS idx_cases_primary_department ON cases(primary_department_id);
CREATE INDEX IF NOT EXISTS idx_cases_lead_investigator ON cases(lead_investigator_id);
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_evidence_items_case ON evidence_items(case_id);
CREATE INDEX IF NOT EXISTS idx_evidence_items_provider ON evidence_items(provider_id);
CREATE INDEX IF NOT EXISTS idx_evidence_items_status ON evidence_items(current_status);
CREATE INDEX IF NOT EXISTS idx_custody_transfers_evidence ON evidence_custody_transfers(evidence_item_id);
CREATE INDEX IF NOT EXISTS idx_documents_case ON documents(case_id);
CREATE INDEX IF NOT EXISTS idx_documents_evidence ON documents(evidence_item_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(document_type);
CREATE INDEX IF NOT EXISTS idx_documents_confidentiality ON documents(confidentiality_level);
CREATE INDEX IF NOT EXISTS idx_document_versions_document ON document_versions(document_id);
CREATE INDEX IF NOT EXISTS idx_document_versions_checksum ON document_versions(sha256_checksum);
CREATE INDEX IF NOT EXISTS idx_document_ai_metadata_version ON document_ai_metadata(version_id);
CREATE INDEX IF NOT EXISTS idx_shares_document ON inter_department_shares(document_id);
CREATE INDEX IF NOT EXISTS idx_shares_target_department ON inter_department_shares(target_department_id);
CREATE INDEX IF NOT EXISTS idx_shares_status_validity ON inter_department_shares(status,valid_from,expires_at);
CREATE INDEX IF NOT EXISTS idx_coc_case_created ON chain_of_custody_logs(case_id,created_at);
CREATE INDEX IF NOT EXISTS idx_coc_document_created ON chain_of_custody_logs(document_id,created_at);
CREATE INDEX IF NOT EXISTS idx_coc_evidence_created ON chain_of_custody_logs(evidence_id,created_at);
CREATE INDEX IF NOT EXISTS idx_coc_actor_created ON chain_of_custody_logs(actor_id,created_at);
CREATE INDEX IF NOT EXISTS idx_signatures_document_version ON digital_signatures(document_version_id);
CREATE INDEX IF NOT EXISTS idx_hearings_case_date ON court_hearings(case_id,hearing_date);
CREATE INDEX IF NOT EXISTS idx_order_sheets_case ON order_sheets(case_id);
CREATE INDEX IF NOT EXISTS idx_court_orders_case ON court_orders(case_id);
CREATE INDEX IF NOT EXISTS idx_court_orders_hearing ON court_orders(hearing_id);
CREATE INDEX IF NOT EXISTS idx_warrants_case ON warrants_and_summons(case_id);
CREATE INDEX IF NOT EXISTS idx_warrants_court_order ON warrants_and_summons(court_order_id);
CREATE INDEX IF NOT EXISTS idx_case_stage_history_case_changed ON case_stage_history(case_id,changed_at);
COMMIT;
